services:
  web:
    build: .
    container_name: sms_web
    ports:
      - "9999:9999"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: sms_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: sms_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci   # ← đã sửa
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sms_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  mysql_data: